# Eat Safe, Love

## Notebook Set Up

In [1]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [6]:
# Find the establishments with a hygiene score of 20
query = {"scores.Hygiene": 20}

# Use count_documents to display the number of documents in the result
print(f"There are {establishments.count_documents(query)} documents with a 'Hygiene' score of 20.")
# Display the first document in the results using pprint
results = establishments.find(query)
print("")
print("The first document is:")
print("-"*50)
pprint(results[0])

There are 82 documents with a 'Hygiene' score of 20.

The first document is:
--------------------------------------------------
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('67a4464c59fcd6899a3eddb7'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [7]:
# Convert the result to a Pandas DataFrame
hygiene_df = pd.json_normalize(results) 
# Display the number of rows in the DataFrame
print(f"The number of rows in this DataFrame is: {len(hygiene_df)}")
print("")
# Display the first 10 rows of the DataFrame
hygiene_df.head(10)

The number of rows in this DataFrame is: 82

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,67a4464c59fcd6899a3eddb7,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,0.276940,50.769705,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,67a4464c59fcd6899a3ee13a,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,1.278721,51.857536,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,67a4464c59fcd6899a3ee442,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,1.159270,51.789429,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,67a4464c59fcd6899a3ee633,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,0.102020,50.770885,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,67a4464c59fcd6899a3ee640,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,0.101446,50.770724,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,67a4464c59fcd6899a3eeff3,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,0.736349,51.541448,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,67a4464c59fcd6899a3ef1fd,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,0.712167,51.535007,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,67a4464d59fcd6899a3f072a,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,0.602364,51.591515,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,67a4464d59fcd6899a3f0b6e,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,0.146450,51.185947,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,67a4464d59fcd6899a3f1384,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,0.462307,51.570050,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [8]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {"LocalAuthorityName":{'$regex': "London"}, "RatingValue" : {'$gte':4}}

# Use count_documents to display the number of documents in the result
print(establishments.count_documents(query)) 
# Display the first document in the results using pprint
results = establishments.find(query)
print("")
print("-"*50)
pprint(results[0])

66

--------------------------------------------------
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('67a4464c59fcd6899a3ef7d1'),
 'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [9]:
# Convert the result to a Pandas DataFrame
london_df = pd.json_normalize(results)
# Display the number of rows in the DataFrame
print(f"The number of rows in this DataFrame is: {len(london_df)}")
print("")
# Display the first 10 rows of the DataFrame
london_df.head(10)

The number of rows in this DataFrame is: 66

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,67a4464c59fcd6899a3ef7d1,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,0.508551,51.369321,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,67a4464c59fcd6899a3efaf7,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,0.249256,51.123623,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,67a4464d59fcd6899a3f0646,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,0.561954,51.543831,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,67a4464d59fcd6899a3f1444,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,0.346325,51.464078,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,67a4464d59fcd6899a3f1451,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,0.346337,51.464066,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,67a4464d59fcd6899a3f1b50,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,0.287555,51.504071,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,67a4464d59fcd6899a3f3c6c,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,0.069286,51.501121,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,67a4464d59fcd6899a3f4026,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,0.048006,51.503733,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,67a4464d59fcd6899a3f403f,295107,0,PI/000020749,City Bar & Grill,Restaurant/Cafe/Canteen,1,London City Airport (Airside),London,,...,0.047966,51.504112,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,67a4464d59fcd6899a3f4040,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,0.047966,51.504112,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [10]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score
lat_long = establishments.find_one({"BusinessName":"Penang Flavours"},{"geocode":1})

degree_search = 0.01
latitude = 51.369321
longitude = 0.508551

query = {"geocode.latitude":{'$gte': latitude-degree_search, '$lte': latitude+degree_search},
        "geocode.longitude":{'$gte': longitude-degree_search, '$lte': longitude+degree_search},
        "RatingValue":5}
sort = [("scores.Hygiene",1)] 
limit = 5

# Print the results
results = list(establishments.find(query).sort(sort).limit(limit))
pprint(results)

[{'AddressLine1': '110 Pattens Lane',
  'AddressLine2': 'Rochester',
  'AddressLine3': 'Kent',
  'AddressLine4': '',
  'BusinessName': 'News Shop',
  'BusinessType': 'Retailers - other',
  'BusinessTypeID': 4613,
  'ChangesByServerID': 0,
  'Distance': 4627.071735597095,
  'FHRSID': 786158,
  'LocalAuthorityBusinessID': 'PI/000030142',
  'LocalAuthorityCode': '896',
  'LocalAuthorityEmailAddress': 'foodandsafety@medway.gov.uk',
  'LocalAuthorityName': 'Medway',
  'LocalAuthorityWebSite': 'http://www.medway.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'ME1 2RA',
  'RatingDate': '2017-09-12T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('67a4464c59fcd6899a3ef5e4'),
  'geocode': {'latitude': 51.366737, 'longitude': 0.516021},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/786158',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 5}},
 {'AddressLine1': '99B Warren Wood Road',
  'AddressLine2': 'Rochester',
  'AddressLine3': 'Medway',
  'AddressLine4': '',
  'BusinessName': 'Warren Wood Social Club',
  'BusinessType': 'Retailers - other',
  'BusinessTypeID': 4613,
  'ChangesByServerID': 0,
  'Distance': 4627.227944225703,
  'FHRSID': 683394,
  'LocalAuthorityBusinessID': 'PI/000187947',
  'LocalAuthorityCode': '896',
  'LocalAuthorityEmailAddress': 'foodandsafety@medway.gov.uk',
  'LocalAuthorityName': 'Medway',
  'LocalAuthorityWebSite': 'http://www.medway.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'ME1 2XA',
  'RatingDate': '2018-09-25T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('67a4464c59fcd6899a3ef69f'),
  'geocode': {'latitude': 51.3600486, 'longitude': 0.5049371},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/683394',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 5}},
 {'AddressLine1': 'Pattens Lane',
  'AddressLine2': 'Rochester',
  'AddressLine3': 'Medway',
  'AddressLine4': '',
  'BusinessName': 'Our Zone',
  'BusinessType': 'Caring Premises',
  'BusinessTypeID': 5,
  'ChangesByServerID': 0,
  'Distance': 4627.191477028352,
  'FHRSID': 1079636,
  'LocalAuthorityBusinessID': '18/00543/CP',
  'LocalAuthorityCode': '896',
  'LocalAuthorityEmailAddress': 'foodandsafety@medway.gov.uk',
  'LocalAuthorityName': 'Medway',
  'LocalAuthorityWebSite': 'http://www.medway.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'ME1 2RB',
  'RatingDate': '2021-09-29T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('67a4464c59fcd6899a3ef65f'),
  'geocode': {'latitude': 51.368408203125, 'longitude': 0.514432013034821},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1079636',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': '1 Beatty Road',
  'AddressLine2': 'Rochester',
  'AddressLine3': 'Kent',
  'AddressLine4': '',
  'BusinessName': 'Papas Fish Bar',
  'BusinessType': 'Takeaway/sandwich shop',
  'BusinessTypeID': 7844,
  'ChangesByServerID': 0,
  'Distance': 4627.165001454627,
  'FHRSID': 605582,
  'LocalAuthorityBusinessID': 'PI/000002322',
  'LocalAuthorityCode': '896',
  'LocalAuthorityEmailAddress': 'foodandsafety@medway.gov.uk',
  'LocalAuthorityName': 'Medway',
  'LocalAuthorityWebSite': 'http://www.medway.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'ME1 2TG',
  'RatingDate': '2020-11-18T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('67a4464c59fcd6899a3ef646'),
  'geocode': {'latitude': 51.363931, 'longitude': 0.510609},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/605582',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 5}},
 {'AddressLine1': '1A Beatty Road',
  'AddressLine2': 'Rochester',
  'AddressLine3': 'Kent',
  'AddressLine4': '',
  'BusinessName': 'One Stop',
  'BusinessType': 'Retailers - other',
  'BusinessTypeID': 4613,
  'ChangesByServerID': 0,
  'Distance': 4627.164964441188,
  'FHRSID': 783911,
  'LocalAuthorityBusinessID': 'PI/000002329',
  'LocalAuthorityCode': '896',
  'LocalAuthorityEmailAddress': 'foodandsafety@medway.gov.uk',
  'LocalAuthorityName': 'Medway',
  'LocalAuthorityWebSite': 'http://www.medway.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'ME1 2TG',
  'RatingDate': '2015-07-21T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('67a4464c59fcd6899a3ef645'),
  'geocode': {'latitude': 51.36393, 'longitude': 0.510609},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/783911',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}]

In [11]:
# Convert result to Pandas DataFrame
penang_df = pd.DataFrame(results) 
penang_df

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,67a4464c59fcd6899a3ef5e4,786158,0,PI/000030142,News Shop,Retailers - other,4613,110 Pattens Lane,Rochester,Kent,...,http://www.medway.gov.uk/,foodandsafety@medway.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.516021, 'latitude': 51.366737}",,4627.071736,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,67a4464c59fcd6899a3ef69f,683394,0,PI/000187947,Warren Wood Social Club,Retailers - other,4613,99B Warren Wood Road,Rochester,Medway,...,http://www.medway.gov.uk/,foodandsafety@medway.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.5049371, 'latitude': 51.3600486}",,4627.227944,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,67a4464c59fcd6899a3ef65f,1079636,0,18/00543/CP,Our Zone,Caring Premises,5,Pattens Lane,Rochester,Medway,...,http://www.medway.gov.uk/,foodandsafety@medway.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.514432013034821, 'latitude': 5...",,4627.191477,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,67a4464c59fcd6899a3ef646,605582,0,PI/000002322,Papas Fish Bar,Takeaway/sandwich shop,7844,1 Beatty Road,Rochester,Kent,...,http://www.medway.gov.uk/,foodandsafety@medway.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.510609, 'latitude': 51.363931}",,4627.165001,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,67a4464c59fcd6899a3ef645,783911,0,PI/000002329,One Stop,Retailers - other,4613,1A Beatty Road,Rochester,Kent,...,http://www.medway.gov.uk/,foodandsafety@medway.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.510609, 'latitude': 51.36393}",,4627.164964,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [12]:
# Create a pipeline that:
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest
match = {'$match': {"scores.Hygiene":0}}

group = {'$group': {"_id" : "$LocalAuthorityName",
                   "count": {'$sum':1}}}

sort = {'$sort':{"count":-1}}

pipeline = [match, group, sort]

results = list(establishments.aggregate(pipeline)) 
# Print the number of documents in the result
print(f"There are {len(results)} documents in the result.")
# Print the first 10 results
print("") 
print("-"*50)
pprint(results[0:10])

There are 55 documents in the result.

--------------------------------------------------
[{'_id': 'Thanet', 'count': 2260},
 {'_id': 'Greenwich', 'count': 1764},
 {'_id': 'Maidstone', 'count': 1426},
 {'_id': 'Newham', 'count': 1422},
 {'_id': 'Swale', 'count': 1372},
 {'_id': 'Chelmsford', 'count': 1360},
 {'_id': 'Medway', 'count': 1344},
 {'_id': 'Bexley', 'count': 1214},
 {'_id': 'Southend-On-Sea', 'count': 1172},
 {'_id': 'Tendring', 'count': 1084}]

In [13]:
# Convert the result to a Pandas DataFrame
zero_hygiene_df = pd.DataFrame(results)
# Display the number of rows in the DataFrame
print(f"There are {len(zero_hygiene_df)} rows in the local authority area dataframe")

# Display the first 10 rows of the DataFrame
zero_hygiene_df.head(10)

There are 55 rows in the local authority area dataframe

               _id  count
0           Thanet   2260
1        Greenwich   1764
2        Maidstone   1426
3           Newham   1422
4            Swale   1372
5       Chelmsford   1360
6           Medway   1344
7           Bexley   1214
8  Southend-On-Sea   1172
9         Tendring   1084